<?php

namespace MassMedia\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCommentsForPost($postId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.post_id = :post_id')
                   ->addOrderBy('c.created_at')
                   ->setParameter('post_id', $postId);

        return $qb->getQuery()
                  ->getResult();
    }
}
