<?php

namespace MassMedia\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {
    public function getPostsForCategory($categoryId) {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.category_id = :category_id')
                   ->addOrderBy('c.name')
                   ->setParameter('category_id', $categoryId);

        return $qb->getQuery()
                  ->getResult();
    }
}
